### ISSUE TITLE
En algunos casos se invierten los valores de costo de oportunidad y valor marginal

### ISSUE THREAD

**Issue by ianv97** [santinozaracho/optimizer-pl-io#5]
Guía TP 1 - Parte III - Tipos de soluciones
Ej 2  (Por si querés mirar la tabla)
 Z = 4X1 + 14X2 -> MAX
 2X1 + 7X2 < 21
 7X1 + 2X2 < 21
Presenta solución alternativa por lo que el costo de oportunidad (en las columnas de las variables reales) debería ser 0 y valor marginal (en las columnas de las slacks) debería ser 2. Da los valores pero invertidos PEEERO...
![Sin título1](https://user-images.githubusercontent.com/38286974/59970193-7f6af780-9536-11e9-824e-1cf2e7f23e4e.jpg)

Ej 3
Max Z=5X1 + 2X2
6X1 + 10X2 <=30
10X1 + 4X2 <= 20
También presenta solución alternativa pero en este caso muestra bien los valores: costo de oportunidad 0 y valor marginal 0,5
![Sin título2](https://user-images.githubusercontent.com/38286974/59970202-97db1200-9536-11e9-8fa2-c8bcdd70e914.jpg)

**Comment by santinozaracho** [comment]
Se soluciono con el commit de la Issue #4 
Solved first case.
![image](https://user-images.githubusercontent.com/40505201/59970445-c9ef7280-953c-11e9-96eb-0764fc5a106c.png)

Solved second case
![image](https://user-images.githubusercontent.com/40505201/59970460-16d34900-953d-11e9-881b-c6d0247cd76a.png)
