### ISSUE TITLE
En algunos casos no muestra costo de oportunidad

### ISSUE THREAD

**Issue by ianv97** [santinozaracho/optimizer-pl-io#6]
Z= 2X1 + 2X2 + X3 -> Maximizar
X1 + 2X2 + 3X3 < 10
X1 - X2 +5X3 > 5
X1 < 1 

![Sin título](https://user-images.githubusercontent.com/38286974/59970353-49c80d80-953a-11e9-89eb-50254f26f4b0.jpg)

**Comment by ianv97** [comment]
En este pasa lo mismo. Los costos de oportunidad son 0 pero en otros cuando era 0 igual lo mostraba.
![Sin título1](https://user-images.githubusercontent.com/38286974/59970430-69f8cc00-953c-11e9-8ef8-e4d9bf5e9e9d.jpg)

![Sin título](https://user-images.githubusercontent.com/38286974/59970429-69f8cc00-953c-11e9-8a74-6dee2c9accb9.jpg)

**Comment by santinozaracho** [comment]
Primer Caso Solved con la Issue #3 
![image](https://user-images.githubusercontent.com/40505201/59970482-9e20bc80-953d-11e9-99be-f000ebfae519.png)

**Comment by santinozaracho** [comment]
> En este pasa lo mismo. Los costos de oportunidad son 0 pero en otros cuando era 0 igual lo mostraba.
> ![Sin título1](https://user-images.githubusercontent.com/38286974/59970430-69f8cc00-953c-11e9-8ef8-e4d9bf5e9e9d.jpg)
> 
> ![Sin título](https://user-images.githubusercontent.com/38286974/59970429-69f8cc00-953c-11e9-8a74-6dee2c9accb9.jpg)

En este caso no existe costo de oportunidad, solo valor marginal tenes solo dos variables y las dos se producen.
![image](https://user-images.githubusercontent.com/40505201/59970493-15565080-953e-11e9-8243-5625a16990a1.png)

**Comment by ianv97** [comment]
Que colgado jajaja disculpá
