### ISSUE TITLE
Explota todo con método gráfico y solución degenerada

### ISSUE THREAD

**Issue by ianv97** [santinozaracho/optimizer-pl-io#7]
Con este literalmente se queda la página en blanco y tira en consola error 404
Usando método gráfico

![Sin título1](https://user-images.githubusercontent.com/38286974/59970472-539f4000-953d-11e9-9c8d-9b816c58c55f.jpg)

**Comment by santinozaracho** [comment]
Se habrá resuelto con algun commit hecho en el dia.
![image](https://user-images.githubusercontent.com/40505201/59970501-49ca0c80-953e-11e9-93c9-dc5cca5c7fe3.png)
